### ISSUE TITLE
Seared Cast duplicated

### ISSUE THREAD

**Issue by Shad0wSlam** [misode/Skymode4#17]
When I broke the Seared Cast, it duplicated. Not sure, nor how to replicate (I was spam clicking though). It may happen with other things too.

**Comment by misode** [comment]
I need a way to reproduce this in order to fix this.

**Comment by Shad0wSlam** [comment]
Well, I spammed the wrench on the cast while standing beside it. It doesn’t happen all the time though. I presume it’s something to do with the cast sometimes being dropped before the armour stand is killed if you click it quick enough.
