### ISSUE TITLE
Zinc becomes steel when transfering to another seared barrel

### ISSUE THREAD

**Issue by Shad0wSlam** [misode/Skymode4#20]
Haven't fully tested, but Zinc becomes Steel, Tin doesn't like exiting a Table, lack of documentation on all of it, no idea how to Alloy but multiple Ore Chunks won't go into the Barrel, etc., so maybe a /give function should be added for everything until it's fixed, in case people want to read documentation and just /give it.

**Comment by Shad0wSlam** [comment]
Tin tool parts also don't leave the table.

**Comment by misode** [comment]
Tin and zinc are metals who only need to be used for alloying, they can't be made into ingots or tool parts. Perhaps there should be a safety check when you try to drain those metals.

**Comment by Shad0wSlam** [comment]
Yeah, I think so then. Also, a lot more documentation is needed on pretty much everything from the Metal Age and onwards.
