### ISSUE TITLE
Solar Panel possible bug

### ISSUE THREAD

**Issue by RagnarPT** [misode/Skymode4#36]
When a SolarPanel is placed alone it produces 8RF every 4 seconds, yet if you place 2 SolarPanel instead of each going up 8RF per 4 seconds, they will bug and 1 will receive the other energy.

Im not sure if the glitch does give more energy but as far as I can see its only affecting which Solar Panel will receive the energy every 4 seconds.

https://youtu.be/WxhWPv7YXvY

This one shows that 4 SolarPanels instead of producing 96RF in 12 seconds (3 (3times of 4 seconds) x 4 machines x 8 RF, they are creating way more.

https://youtu.be/hL0RH7KpmKY

Note: All this info was made on the assumption that Solar Panels produce 8RF per 4 seconds as shown in the first video.

**Comment by RagnarPT** [comment]
UPDATE: I placed a Capacitor bank and the SolarPanel started generating a lot more Energy than if it was the only machine.

**Comment by misode** [comment]
> When a SolarPanel is placed alone it produces 8RF every 4 seconds, yet if you place 2 SolarPanel instead of each going up 8RF per 4 seconds, they will bug and 1 will receive the other energy.

> UPDATE: I placed a Capacitor bank and the SolarPanel started generating a lot more Energy than if it was the only machine.

Cannot reproduce either of these issues. The current implementation is random so that might explain the effects you're seeing. If you watch the energy levels you'll see that the difference is not so big anymore
