### ISSUE TITLE
metals

### ISSUE THREAD

**Issue by kaitlyn65** [misode/Skymode4#38]
what is the point of the brass, zinc, tin, and bronze? we can't seem to retrieve it out of the seared table. we're also experiencing difficulties making the brass and bronze. 

also unrelated, what is the point of the rocks?

**Comment by misode** [comment]
I have to admit that these mechanics aren't well explained atm.

> what is the point of the brass, zinc, tin, and bronze?

You can only take out steel and copper in ingot form. You can take out brass, copper, steel and bronze if they are in a mold. Zinc and tin are only used to make alloys.

> what is the point of the rocks?

You can make cobblestone by throwing 4 rocks on the ground. I plan on making this a crafting recipe to avoid confusion.
