### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by jessecarvalho89** [misode/Skymode4#39]
Are we supposed to figure everything out on our own or are we supposed to use the wiki. i ask because of a few things

1. Where do i get silver ore? cant figure it out

2. Can i somehow spawn animals? is that possible? how could i get slimes? how can i get diamonds?

**Comment by jessecarvalho89** [comment]
Also, when i make other metals like bronze and copper molds(ax heads and stuff) how do i actually put it together?

**Comment by misode** [comment]
I'm currently working on a manual in game, but atm you have to look at the wiki for most of the information.

1. You get ore chunks from crushing gravel in a crusher.
2. If you're further than 30 blocks away, passive mobs can spawn on grass blocks and hostile mobs can spawn in dark area's. 
3. As for slimes, the only way would be to find a slime chunk and build a platform in the void. This is not ideal so maybe I should make a module to summon slimes.
4. You can't get diamonds atm, but you can make other good tools (eg. steel tools) which are even better.

**Comment by jessecarvalho89** [comment]
Thank you for answering my questions. I was asking about diamonds so i could make other things like enchanting tables and stuff
