### ISSUE TITLE
Fans not working on mobs (althought still works on players)

### ISSUE THREAD

**Issue by DivineWarrior1234** [misode/Skymode4#40]

**Comment by misode** [comment]
@DivineWarrior1234 Thanks for reporting this! This issue is fixed in v0.6.2
You can get this version here: https://github.com/misode/Skymode4/releases/tag/v0.6.2-alpha

**Comment by DivineWarrior1234** [comment]
Thanks for noticing the issue! Apart from that, the map is very enjoyable
and fun to play :)
