### ISSUE TITLE
A few things that need fixing.

### ISSUE THREAD

**Issue by EnderSlime123** [misode/Skymode4#42]
Wrench can't break machines, and its right click ability has no use. A give command would also be nice for people who want to showcase this pack.

Items also cannot be added to barrels when I'm doing what the Wiki says.

Electric Furnace doesn't smelt anything and just gets stuck.

Custom Tools tab takes me to the home page.

The Skymode manual has no recipe and has pages that say null or are blank.

There's also no way to pour molten metals from a seared barrel.

![2019-03-02_15 10 30](https://user-images.githubusercontent.com/47653006/53688743-5f03fc80-3cfd-11e9-8813-f8ce4120f16a.png)

**Comment by ArnyminerZ** [comment]
Your issue with barrels is fixed in the [Pull Commit 44](https://github.com/misode/Skymode4/pull/44)

**Comment by MagmaSlime123** [comment]
@ArnyminerZ What about the 99999 other issues.

**Comment by ArnyminerZ** [comment]
I'm not a maintainer xD. I've just fixed some things I could figure out. I don't know how the project works at all. Sorry bro

**Comment by misode** [comment]
Closing as this project was never updated to 1.14 in the first place. It will be updated to 1.14 eventually.
